-- Up

CREATE TABLE IF NOT EXISTS user (
	pk_id_user	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	fk_id_guest	INTEGER NOT NULL DEFAULT 0,
	login	TEXT NOT NULL,
	password	TEXT NOT NULL,
	nickname	TEXT NOT NULL,
	NORM_nickname	TEXT NOT NULL,
	fk_id_avatar	INTEGER NOT NULL DEFAULT 0,
	bio	TEXT,
	url	TEXT,
	email	TEXT,
	fingerprint	TEXT,
	guest_expires	INTEGER NOT NULL,
	flag_online	INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS avatar (
	pk_id_avatar	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	type	INTEGER NOT NULL DEFAULT 1,
	imagefile	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS guest (
	pk_id_guest	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name	TEXT NOT NULL,
	fk_id_avatar	INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS favorites (
	fk_id_user	INTEGER NOT NULL,
	fk_id_kara	INTEGER NOT NULL,
	kid	TEXT NOT NULL,
	duration	INTEGER NOT NULL DEFAULT 0
);

-- Down

DROP TABLE IF EXISTS guest;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS avatar;
DROP TABLE IF EXISTS user;
