-- Up

CREATE TABLE IF NOT EXISTS user (
	pk_id_user	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	type	INTEGER NOT NULL DEFAULT 1,
	login	TEXT NOT NULL,
	password	TEXT,
	nickname	TEXT NOT NULL,
	NORM_nickname	TEXT NOT NULL,
	avatar_file	TEXT NOT NULL DEFAULT 'blank.jpg',
	bio	TEXT,
	url	TEXT,
	email	TEXT,
	fingerprint	TEXT,
	last_login	INTEGER NOT NULL,
	flag_online	INTEGER NOT NULL DEFAULT 0,
	flag_admin INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS favorites (
	fk_id_user	INTEGER NOT NULL,
	fk_id_kara	INTEGER NOT NULL,
	kid	TEXT NOT NULL,
	duration	INTEGER NOT NULL DEFAULT 0
);

-- Down

DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS user;
