approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - linux
    - win32
    - darwin

yarnPath: .yarn/releases/yarn-4.18.0.cjs
