System:
  Database:
    bundledPostgresBinary: false
    database: karaokemugen_app
    host: postgres
    password: musubi
    port: 5432
    superuser: karaokemugen_app
    superuserPassword: musubi
    username: karaokemugen_app
    connection: tcp
  Repositories:
    Name: mugen.re
    Online: true
    Secure: true
    Update: true
    Enabled: true
    SendStats: true
    AutoMediaDownloads: updateOnly
    MaintainerMode: false
    BaseDir: repos/mugen.re/json
    Path:
      Medias: 
        - repos/mugen.re/medias
  Binaries:
    Player:
      Linux: mpv
    ffmpeg:
      Linux: ffmpeg
    patch:
      Linux: patch
