ALTER TABLE playlist ADD COLUMN IF NOT EXISTS songs_played INTEGER DEFAULT 0;
ALTER TABLE playlist ADD COLUMN IF NOT EXISTS songs_left INTEGER DEFAULT 0;
ALTER TABLE playlist ADD COLUMN IF NOT EXISTS time_played INTEGER DEFAULT 0;