ALTER TABLE playlist ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE playlist ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE playlist ADD COLUMN IF NOT EXISTS nickname TEXT;
ALTER TABLE playlist ADD COLUMN IF NOT EXISTS contributors JSONB[];