import { DBKara } from '../../../src/lib/types/database/kara';

export const karaokeExample: DBKara = {
	kid: '4753c766-8d1c-496b-a3c3-50a117c707ce',
	titles: { jpn: 'おうちに帰りたい', qro: 'Ouchi ni Kaeritai' },
	titles_default_language: 'qro',
	hardsubbed_mediafile: '4753c766-8d1c-496b-a3c3-50a117c707ce.12322132.691f7cdba1e7e03bd26a8d6411a52ccd.mp4',
	titles_aliases: ['wanna go home'],
	songorder: null,
	lyrics_infos: [{ default: true, version: 'Default', filename: '4753c766-8d1c-496b-a3c3-50a117c707ce.ass' }],
	year: 2017,
	mediafile: '4753c766-8d1c-496b-a3c3-50a117c707ce.mp4',
	karafile: '4753c766-8d1c-496b-a3c3-50a117c707ce.kara.json',
	duration: 89,
	loudnorm: '-16.06,-6.08,3.10,-26.10,-0.72',
	created_at: '2025-04-18T23:25:30.269Z',
	modified_at: '2025-04-19T00:23:18.256Z',
	mediasize: 12322132,
	repository: 'mugen.re',
	ignore_hooks: false,
	anilist_ids: ['21699'],
	myanimelist_ids: ['32937'],
	kitsu_ids: ['11937'],
	from_display_type: null,
	subchecksum: '691f7cdba1e7e03bd26a8d6411a52ccd',
	songname: 'JPN - Kono Subarashii Sekai ni Shukufuku wo! 2 - ED - Ouchi ni Kaeritai ~ Kana Vers',
	playlists: [],
	parents: ['27c2c99d-3a3c-4f1d-a425-ddcda1956f84'],
	children: [],
	siblings: [],
	count: 1,
	series: [
		{
			tid: '74b4a549-f5fb-4d6d-88ac-01bbaf265448',
			i18n: {
				eng: "Konosuba: God's Blessing on This Wonderful World! 2",
				fre: 'Konosuba : Sois béni monde merveilleux ! (saison 2)',
				jpn: 'この素晴らしい世界に祝福を! 2',
				kor: '이 멋진 세계에 축복을! 2',
				qro: 'Kono Subarashii Sekai ni Shukufuku wo! 2',
			},
			name: 'Kono Subarashii Sekai ni Shukufuku wo! 2',
			short: null,
			aliases: ['konosuba 2', 'Этот замечательный мир! ТВ2'],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 1,
			noLiveDownload: false,
			external_database_ids: { kitsu: 11937, anilist: 21699, myanimelist: 32937 },
		},
	],
	singers: [
		{
			tid: '6c2557cb-9bde-4bad-b5a6-8af24a080047',
			i18n: { eng: 'Sora Amamiya' },
			name: 'Sora Amamiya',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 2,
			noLiveDownload: false,
			external_database_ids: null,
		},
		{
			tid: 'a0ac6bca-c73a-49d9-956f-3378f1d6fe8c',
			i18n: { eng: 'Rie Takahashi', jpn: '高橋 李依', qro: 'Takahashi Rie' },
			name: 'Rie Takahashi',
			short: null,
			aliases: ['rieri'],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 2,
			noLiveDownload: false,
			external_database_ids: null,
		},
		{
			tid: 'd2bf0734-aede-4e5c-b3a6-6d68b18192dc',
			i18n: { eng: 'Ai Kayano', jpn: '茅野 愛衣', qro: 'Kayano Ai' },
			name: 'Ai Kayano',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 2,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	songtypes: [
		{
			tid: '38c77c56-2b95-4040-b676-0994a8cb0597',
			i18n: {
				eng: 'Ending',
				fre: 'Ending',
				ger: 'Ending',
				ita: 'Ending',
				jpn: 'エンディングテーマ',
				pol: 'Końcówka',
				por: 'Final',
				tam: 'முடிவு',
			},
			name: 'ED',
			short: null,
			aliases: [],
			priority: 15,
			repository: 'mugen.re',
			description: {
				eng: 'End credits',
				fre: 'Générique de fin d’une œuvre',
				ger: 'End Credits',
				ita: 'Crediti finali',
			},
			karafile_tag: 'ED',
			type_in_kara: 3,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	creators: [
		{
			tid: '2bf7a71d-d3fc-42ba-8aa0-a94d7ca3888c',
			i18n: { eng: 'Studio DEEN' },
			name: 'Studio DEEN',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 4,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	langs: [
		{
			tid: '4dcf9614-7914-42aa-99f4-dbce2e059133',
			i18n: {
				afr: 'Japanees',
				alb: 'Japoneze',
				amh: 'ጃፓንኛ',
				ara: 'اليابانية',
				arm: 'Ճապոներեն',
				aze: 'Yapon',
				bak: 'Япон теле',
				baq: 'Japoniako',
				bel: 'Японскі',
				ben: 'জাপানি',
				bos: 'Japanci',
				bul: 'Японски',
				cat: 'Japonès',
				chi: '日本',
				cze: 'Japonské',
				dan: 'Japansk',
				dut: 'Japans',
				eng: 'Japanese',
				epo: 'Japana',
				est: 'Jaapani',
				fin: 'Japanilainen',
				fre: 'Japonais',
				geo: 'იაპონელი',
				ger: 'Japanisch',
				gla: 'Italian',
				gle: 'Seapáinis',
				glg: 'Xaponés',
				gre: 'Ιαπωνικά',
				guj: 'જાપાનીઝ',
				hat: 'Japonè',
				heb: 'יפנית',
				hin: 'जापानी',
				hrv: 'Japanski',
				hun: 'Japán',
				ice: 'Japanska',
				ind: 'Jepang',
				ita: 'Giapponese',
				jav: 'Jepang',
				jpn: '日本語',
				kan: 'ಜಪಾನೀಸ್',
				kaz: 'Жапон',
				kir: 'Японский',
				kor: '일본어',
				lat: 'Facilisis',
				lav: 'Japāņu',
				lit: 'Japonų',
				mac: 'Јапонски',
				mal: 'ജാപ്പനീസ്',
				mao: 'Hapanihi',
				mar: 'जपानी',
				may: 'Jepun',
				mlg: 'Japoney',
				mlt: 'Ġappuniż',
				mon: 'Японы',
				nep: 'जापानी',
				nor: 'Japansk',
				pan: 'ਜਪਾਨੀ',
				per: 'ژاپنی',
				pol: 'Japoński',
				por: 'Japonês',
				rum: 'Japoneze',
				rus: 'Японский',
				sin: 'ජපන්',
				slo: 'Japonský',
				slv: 'Japonski',
				spa: 'Japonés',
				srp: 'Јапански',
				sun: 'Jepang',
				swa: 'Kijapani',
				swe: 'Japanska',
				tam: 'ஜப்பனீஸ்',
				tat: 'Япон теле',
				tel: 'జపనీస్',
				tgk: 'Ҷопон',
				tgl: 'Hapon',
				tha: 'ภาษาญี่ปุ่น',
				tur: 'Japon',
				ukr: 'Японський',
				urd: 'جاپانی',
				uzb: 'Yaponiya',
				vie: 'Nhật bản',
				wel: 'Siapan',
				xho: 'Isijapanese',
				yid: 'יאַפּאַניש',
			},
			name: 'jpn',
			short: 'JPN',
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 5,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	authors: [
		{
			tid: '5690b59e-e9d1-4384-8a50-f0ff04996dfb',
			i18n: { eng: 'tcyrus' },
			name: 'tcyrus',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 6,
			noLiveDownload: false,
			external_database_ids: null,
		},
		{
			tid: 'c4255606-fb63-4f55-a44b-698c8ce17e04',
			i18n: { eng: 'Malorn44' },
			name: 'Malorn44',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 6,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	misc: [
		{
			tid: '1d6ceadf-a885-47e5-b23b-c07bf668a424',
			i18n: {
				eng: 'Group Singing',
				fre: 'Chant en groupe',
				ger: 'Gruppengesang',
				ita: 'Canti di gruppo',
				pol: 'Śpiew grupowy',
				por: 'Canto em grupo',
				tam: 'குழு பாடல்',
			},
			name: 'Group',
			short: 'GROUP',
			aliases: ['Duo', 'trio', 'duet'],
			priority: 10,
			repository: 'mugen.re',
			description: {
				eng: 'Karaoke designed to be performed by several people',
				fre: 'Karaoke conçu pour être chanté à plusieurs',
				ger: 'Karaoke für mehrere Sänger',
				ita: 'Karaoke pensato per più di una persona',
				pol: 'Karaoke przeznaczone do wykonania przez kilka osób',
				por: 'Karaokê concebido para ser cantado por múltiplas pessoas',
				spa: 'Karaoke diseñado para ser cantados por varias personas',
				tam: 'கரோக்கி பலரால் செய்ய வடிவமைக்கப்பட்டுள்ளது',
			},
			karafile_tag: null,
			type_in_kara: 7,
			noLiveDownload: false,
			external_database_ids: null,
		},
		{
			tid: 'fe819ff1-9db8-4a0f-85dc-0e322c9126c4',
			i18n: {
				bre: 'Hep kredad',
				eng: 'Creditless',
				fre: 'Sans crédit',
				ger: 'Creditless',
				ita: 'Senza crediti',
				pol: 'Bez kredytu',
				por: 'Sem crédito',
				spa: 'Sin creditos',
				tam: 'C reji t -s',
			},
			name: 'Creditless',
			short: 'CRED',
			aliases: [],
			priority: -1,
			repository: 'mugen.re',
			description: {
				eng: 'Media from which all credits have been removed except for the work’s logo, only for OP/ED',
				fre: 'Média dont tous les crédits ont été retirés sauf le logo de l’œuvre, uniquement pour les OP/ED',
				ger: 'Medien, in denen alle Credits entfernt wurden außer dem Logo des Titels, nur für OP/ED',
				ita: "Video da cui sono stati rimossi tutti i crediti tranne il logo dell'opera, solo per OP/ED.",
				pol: 'Nośniki, z których usunięto wszystkie napisy końcowe z wyjątkiem logo, tylko dla OP/ED',
				spa: 'Media en la que todos los creditos han sido borrados exceptuando el logo de la obra, solo para OP/ED',
				tam: 'OP/ED க்கு மட்டுமே, பணியின் சின்னத்தைத் தவிர அனைத்து வரவுகளும் அகற்றப்பட்ட மீடியா',
			},
			karafile_tag: null,
			type_in_kara: 7,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	songwriters: [
		{
			tid: '7df923b4-4429-4123-950a-50dede56b016',
			i18n: { eng: 'Ryôsei Satô' },
			name: 'Ryôsei Satô',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 8,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	groups: [
		{
			tid: 'ae613721-1fbe-480d-ba6b-d6d0702b184d',
			i18n: {
				bre: 'Bloavezhioù 2010',
				eng: '2010s',
				fre: 'Années 2010',
				ger: '2010er',
				ita: 'Anni 2010',
				jpn: '2010年代',
				pol: 'Lata 2010',
				por: 'década de 2010',
				tam: '2010 கள்',
			},
			name: '2010s',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 9,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	families: [
		{
			tid: '0377db02-3af6-43b8-9b08-c759df3d25c3',
			i18n: {
				eng: 'Animation',
				fre: 'Animation',
				ger: 'Animation',
				ita: 'Animazione',
				jpn: 'アニメーション',
				pol: 'Animacja',
				por: 'Animação',
				spa: 'Animación',
				tam: 'அனிமேசன்',
			},
			name: 'Animation',
			short: 'ANIM',
			aliases: ['Anime', 'Cartoon'],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 10,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	origins: [
		{
			tid: '938de218-5343-4865-94d3-fb33f2eaa152',
			i18n: {
				bre: 'Heuliad Skinwel',
				eng: 'TV Series',
				fre: 'Série TV',
				ger: 'Fernsehserie',
				ita: 'Serie TV',
				pol: 'Seriale telewizyjne',
				por: 'Série de TV',
				tam: 'தொலைக்காட்சி தொடர்',
			},
			name: 'TV Series',
			short: 'SERIE',
			aliases: ['Drama'],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 11,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	genres: [
		{
			tid: '4b80eca6-f44f-4262-a8d0-b6879d6b70cb',
			i18n: {
				bre: 'Isekai',
				eng: 'Isekai',
				fre: 'Isekai',
				ger: 'Isekai',
				ita: 'Isekai',
				jpn: '異世界',
				pol: 'Isekai',
				por: 'Isekai',
				qro: 'Isekai',
				tam: 'வெவ்வேறு உலகம்',
			},
			name: 'Isekai',
			short: 'ISK',
			aliases: ['いせかい'],
			priority: 10,
			repository: 'mugen.re',
			description: {
				eng: 'Work whose plot essentially consists of a character who is sent to a parallel world',
				fre: 'Œuvre dont l’intrigue consiste principalement en un personnage envoyé vers un monde parallèle',
				ger: 'Werke, deren Inhalt sich im Wesentlichen darauf bezieht, dass Charaktere in Parallelwelten geschickt werden',
				ita: 'Opera che tratta un personaggio che viene mandato in un mondo parallelo',
				pol: 'Dzieło, którego fabuła zasadniczo składa się z postaci, która zostaje wysłana do równoległego świata',
				tam: 'ஒரு இணையான உலகத்திற்கு அனுப்பப்படும் ஒரு பாத்திரத்தை அதன் சூழ்ச்சி அடிப்படையில் கொண்டுள்ளது',
			},
			karafile_tag: null,
			type_in_kara: 12,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	platforms: [],
	versions: [
		{
			tid: '12d21e9c-3427-4677-a5bd-1301a0f7358a',
			i18n: {
				bre: 'Kana',
				eng: 'Kana',
				fre: 'Kana',
				ger: 'Kana',
				ita: 'Kana',
				jpn: 'カナ',
				pol: 'Kana',
				por: 'Kana',
				tam: 'கனா',
			},
			name: 'Kana',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {
				eng: 'Hard mode, karaokes with the Japanese alphabet',
				fre: "Hard mode, les karaokes avec l'alphabet japonais",
				ger: 'Sehr schwer: Karaoke mit japanischem Alphabet',
				ita: 'Modalità difficile, karaoke scritti in caratteri giapponesi.',
				pol: 'Tryb trudny, karaoke z alfabetem japońskim',
				por: 'Modo difícil, karaokês com o alfabeto japonês',
				tam: 'கடின பயன்முறை, சப்பானிய எழுத்துக்களுடன் கரோக்ச்',
			},
			karafile_tag: null,
			type_in_kara: 14,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
	warnings: [],
	collections: [
		{
			tid: 'f2462778-f986-4844-a4b8-e1d3ccdb861b',
			i18n: {
				bre: 'Kana',
				eng: 'Kana',
				fre: 'Kana',
				ger: 'Kana',
				ita: 'Kana',
				jpn: 'カナ',
				pol: 'Kana',
				por: 'Kana',
				tam: 'கனா',
			},
			name: 'Kana',
			short: null,
			aliases: [],
			priority: 10,
			repository: 'mugen.re',
			description: {
				eng: 'Japanese songs with kana karaoke',
				fre: 'Chansons japonaises avec paroles en kana',
				ger: 'Japanische Lieder mit Kana-Karaoke',
				ita: 'Karaoke giapponesi scritti in kana',
				pol: 'Japońskie piosenki z zapisem karaoke znakami kana',
				por: 'Canções japonesas com kana karaokê',
				tam: 'கானா கரோக்கியுடன் சப்பானிய பாடல்கள்',
			},
			karafile_tag: null,
			type_in_kara: 16,
			noLiveDownload: true,
			external_database_ids: null,
		},
	],
	singergroups: [],
	franchises: [
		{
			tid: '5a673b40-0313-456f-bb07-9409d4dd95cc',
			i18n: {
				eng: "Konosuba: God's Blessing on This Wonderful World!",
				fre: 'Konosuba : Sois béni monde merveilleux !',
				jpn: 'この素晴らしい世界に祝福を!',
				kor: '이 멋진 세계에 축복을!',
				qro: 'Kono Subarashii Sekai ni Shukufuku wo!',
			},
			name: 'Kono Subarashii Sekai ni Shukufuku wo!',
			short: null,
			aliases: ['konosuba', 'Этот замечательный мир!', '为美好的世界献上祝福!'],
			priority: 10,
			repository: 'mugen.re',
			description: {},
			karafile_tag: null,
			type_in_kara: 18,
			noLiveDownload: false,
			external_database_ids: null,
		},
	],
} as unknown as DBKara;
